---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: flake8
      - id: check-yaml
        files: .*\.(yaml|yml)$
        args: [--unsafe]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        # uncomment once a new yamllint release is made:
        # entry: yamllint --strict
  - repo: https://github.com/openstack-dev/bashate.git
    rev: 0.6.0
    hooks:
      - id: bashate
        entry: bashate --error . --ignore=E006,E040
        # Run bashate check for all bash scripts
        # Ignores the following rules:
        # E006: Line longer than 79 columns (as many scripts use jinja
        #       templating, this is very difficult)
        # E040: Syntax error determined using `bash -n` (as many scripts
        #       use jinja templating, this will often fail and the syntax
        #       error will be discovered in execution anyway)
