---
# see https://docs.ansible.com/ansible/latest/reference_appendices/galaxy.html#installing-multiple-roles-from-a-file

# from galaxy
# - src: avinetworks.docker

# - src: https://opendev.org/zuul/zuul-jobs.git

- src: https://github.com/DataDog/ansible-datadog.git
- src: geerlingguy.nfs
