---
- setup:
    filter: "*"
  when: ansible_pkg_mgr is not defined

- name: configure system proxy variables
  copy:
    dest: /etc/profile.d/proxy.sh
    content: |
      HTTP_PROXY={{ http_proxy }}
      HTTPS_PROXY={{ http_proxy }}
      http_proxy={{ http_proxy }}
      https_proxy={{ http_proxy }}
      ftp_proxy={{ http_proxy }}
      export http_proxy https_proxy ftp_proxy HTTP_PROXY HTTPS_PROXY

- name: configure wget proxy
  copy:
    dest: /etc/wgetrc
    content: |
      http_proxy = {{ http_proxy }}
      https_proxy = {{ http_proxy }}
      ftp_proxy = {{ http_proxy }}

- name: configure packager proxy
  ini_file:
    path: "{{ pkg_mgr_map[ansible_pkg_mgr] }}"
    section: main
    option: proxy
    value: "http://{{ http_proxy }}"

- name: install custom CA
  copy:
    dest: /etc/pki/ca-trust/source/anchors/custom-ca.crt
    content: "{{ custom_ca }}"
  register: result

- name: activate custom CA
  when: result is changed
  shell: update-ca-trust

- name: configure pip to use system ca certificates
  ini_file:
    path: "/etc/pip.conf"
    section: global
    option: cert
    value: "/etc/ssl/certs/ca-bundle.crt"