---
# TODO:
# PermitRootLogin=yes into /etc/ssh/sshd_config
# Restart sshd: sudo synoservicectl --restart sshd
# needed to be able to rsync ssl certs from router

- include_tasks: tftp.yml

- include_tasks: ssl.yml

# - include_tasks: docker.yml

# kudos to: https://nguvu.org/pfsense/pfSense-WPAD-PAC-proxy-configuration-guide/
- name: configure proxy wpad file
  template:
    src: proxy.pac.j2
    dest: "{{ ks_root }}/proxy.pac"

- name: proxy wpad symlinks
  file:
    dest: "{{ ks_root }}/{{ item }}"
    src: "{{ ks_root }}/proxy.pac"
    state: link
    # force: true
  with_items:
    - wpad.dat
    - wpad.da
