---
- name: gather facts for ssl
  setup:
    gather_subset: min

- name: sync certificates
  copy:
    src: secrets/{{ cert_name }}.pem
    dest: /usr/syno/etc/certificate/system/default/_cert.pem
  become: true

- debug:
    var: result
