---
- setup:
    gather_subset: min
    # min includes ansible_python_version
# cert.pem\nchain.pem\nfullchain.pem\nprivkey.pem
# - shell: |
#     ls /usr/syno/etc/certificate/system/default
#   register: result

# - package:
#     name: rsync
#     use: pkg
#   delegate_to: pfsense
#   become: yes

- synchronize:
    src: /conf/acme/{{ cert_name }}.crt
    dest: /usr/syno/etc/certificate/system/default/_cert.pem
    set_remote_user: false
    use_ssh_args: true
  delegate_to: pfsense
  become: true

- debug:
    var: result
