# Based on a true story from
# https://blog.bobbyallen.me/2013/02/03/how-to-redirect-local-root-mail-to-an-external-email-address-on-linux/
- name: forward root email
  become: yes
  lineinfile:
    dest: /etc/aliases
    regexp: "^(.*)root:(.*)"
    line: "root:  {{ sysadmin_email }}"
  register: result

- when: result is changed
  block:

    - name: gather ansible_hostname
      setup:
        gather_subset:
          - '!all'

    - name: install mail related packages
      package:
        name: 
          - postfix
          - mailx
        state: installed

    - name: call newaliases
      become: yes
      command: /usr/bin/newaliases
  
    - name: restart postfix
      become: yes
      service:
        name: postfix
        state: restarted
        enabled: yes

    - name: sent test email
      become: yes
      shell: |
        echo 'ansible configured email on {{ ansible_hostname }}' | mail -s '{{ ansible_hostname }}: ansible test' root
