---
# vars file for dsm
distros_mirror: http://mirror.bytemark.co.uk
http_proxy: 192.168.33.1:3128
# ks_url is where the kickstart files are served from
ks_url: http://192.168.33.40/~ssbarnea/ks
ks_root: /volume1/homes/ssbarnea/www/ks
pxe_root: /volume2/PXE

# Use `openssl passwd -1 "password"` to generate a new password
# rootpw: "--iscrypted $6$...."
# auth_encryption: --passalgo=sha512
rootpw: "--plaintext {{ root_password }}"

default_username: cloud-user
default_password: "{{ root_password }}"

authorized_keys: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
ipv6: false
snmp: false

nameserver: ~  # define it if you want to configure a default nameserver
domain: lan
search_domains: "{{ domain}}"

kernel_options: >
  nomodeset
  i915.modeset=0
  nouveau.modeset=0
  logo.nologo
  inst.cmdline
  inst.proxy=http://{{ http_proxy }}
  console=tty0
  modprobe.blacklist=floppy
# console=ttyS0,115200
# console=ttyS0

#   quiet  # not desired as it will replace the boot mesages is a progress bar

# ksdevice=bootif - does nothing

# inst.cmdline
# see https://serverfault.com/questions/708447/probing-edd-boot-message-stays-for-ten-minutes-on-centos-6-6


# -- not implemented yet --

dhcp_boot_default_bios_filename: pxelinux.0
# undionly.kpxe  # ipxe file (causes recursive loop without special config on dhcp server)
dhcp_boot_uefi_32bit_filename: centos/efi/grubia32.efi
dhcp_boot_uefi_64bit_filename: centos/efi/grubx64.efi
dhcp_boot_next_server: 192.168.33.40

extra_packages:
  - htop
  - iotop
  - mc
  - ncdu
