---
# tasks file for ensure-docker
- name: load required facts
  setup:
    gather_subset: min
    # min includes ansible_python_version
# cert.pem\nchain.pem\nfullchain.pem\nprivkey.pem
# - shell: |
#     ls /usr/syno/etc/certificate/system/default
#   register: result

- debug: var=ansible_distribution
# - docker_swarm:
#     state: present
# - import_role:
#     name: avinetworks.docker
- name: install docker dependencies
  package:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
  become: true

# - package:
#     name: rsync
#     use: pkg
#   delegate_to: pfsense
#   become: yes
# - name: configure docked
#   template:
#     src: dockerd.json.j2
#     dest: /var/packages/Docker/etc/dockerd.json
#   register: result
#   become: true

- debug: var=result


- name: run install-docker role from zuul-jobs
  include_role:
    name: install-docker
