http:
  routers:
    syno-http:
      rule: Host(`syno.sbarnea.com`)
      service: syno
      middlewares:
        - redirect
      entrypoints:
        - http
    syno-https:
      rule: Host(`syno.sbarnea.com`)
      tls:
        certresolver: myresolver
      service: syno
      entrypoints:
        - https
    z:
      rule: Host(`z.sbarnea.com`)
      service: dashboard@internal
      tls:
        certresolver: myresolver
      entrypoints:
        - http
        - https
  services:
    syno:
      loadBalancer:
        servers:
          url: "http://192.168.33.40"

  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
