---
# https://unix.stackexchange.com/questions/212894/whats-the-right-format-for-the-http-proxy-environment-variable-caps-or-no-ca
- hosts: leno
  gather_facts: true
  strategy: free
  become: true
  tasks:
    - include_role:
        name: ensure-proxy
      # - include_role:
      #     name: ensure
      # - include_role:
      #     name: monitoring
