---
- hosts: all
  connection: local
  gather_facts: true
  strategy: linear
  vars:
    state: "on"
  tasks:

    - name: configure next boot device
      ipmi_boot:
        bootdev: "{{ state }}"
        # network
        # setup
        # network
        name: "{{ ipmi_address }}"
        uefiboot: no
        user: "{{ ipmi_user }}"
        password: "{{ ipmi_password }}"
      delegate_to: localhost
      when: state != "on"
      register: ipmi_boot

    - name: reboot
      ipmi_power:
        name: "{{ ipmi_address }}"
        user: "{{ ipmi_user }}"
        password: "{{ ipmi_password }}"
        state: "{% if state == 'setup' %}boot{% elif state %}on{% else %}off{% endif %}"
        timeout: 10
      register: ipmi_power

    - debug:
        msg: "{{ ipmi_boot }} {{ ipmi_power }}"
