#!/usr/bin/env ansible-playbook
---
# playbook to configure the pfsense router, 'q'
- hosts: q
  gather_facts: false
  tasks:
    # - name: mc command workaround
    #   lineinfile:
    #     path: /root/.tcshrc
    #     state: present
    #     regexp: '^alias mc '
    #     line: alias mc 'mc -u'
    #     # ^ use of single quotes is a MUST for alias to work

    # - name: router role
    #   import_role:
    #     name: router
    - name: deploy otpd script
      become: true
      copy:
        dest: /root/otpd
        mode: a+rx
        content: |
          #!/usr/bin/env sh
          (
            # SCRIPT=`realpath $0`     # get absolute path to the script itself
            # exec 6< "$SCRIPT"        # open bash script using file descriptor 6
            # flock -n 6 || 
            while true
            do
            printf "ssbarnea\n5baltair`oathtool --totp -b IJFKSLSL5MOLQXOWUNUW7RRE5VCVAHJ2`" > /tmp/.ovpn-tmp
            sleep 30
            done
          ) &

    - name: configure openvpn otpd service
      become: true
      copy:
        dest: /usr/local/opnsense/service/conf/actions.d/actions_otpd.conf
        content: |
          [start]
          command:/bin/pkill -f otpd; /root/otpd
          parameters:
          type:script
          message:starting otpd
          description: Start OTPD

          [restart]
          command:/bin/pkill -f otpd; /root/otpd
          parameters:
          type:script
          message:starting otpd
          description: Restart OTPD

          [stop]
          command:/bin/pkill -f otpd; exit 0
          parameters:
          type:script
          message:stop otpd
          description: Stop OTPD

      register: result

    - name: reload config
      when: result is changed
      become: true
      command: service configd restart
      args:
        warn: false

    - name: restart otdp
      when: result is changed
      command: configctl otpd restart
      args:
        creates: /tmp/.ovpn-tmp

    - name: assure file mod
      file:
        path: /tmp/.ovpn-tmp
        mode: 0600
      become: true
      register: result
      until: result is success
      retries: 5
      delay: 5

    - name: restart openvpn
      become: true
      shell: openvpn --config /var/etc/openvpn/client1.conf
      when: result is changed
